// v1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.22.3
// source: client.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: db:"ID"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" db:"ID"`
	// @gotags: db:"DBPolicy"
	DBPolicy int32 `protobuf:"varint,2,opt,name=DBPolicy,proto3" json:"DBPolicy,omitempty" db:"DBPolicy"`
	// @gotags: db:"Level"
	Level         LogLevel `protobuf:"varint,3,opt,name=Level,proto3,enum=logs.LogLevel" json:"Level,omitempty" db:"Level"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogClient) Reset() {
	*x = LogClient{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogClient) ProtoMessage() {}

func (x *LogClient) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogClient.ProtoReflect.Descriptor instead.
func (*LogClient) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *LogClient) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogClient) GetDBPolicy() int32 {
	if x != nil {
		return x.DBPolicy
	}
	return 0
}

func (x *LogClient) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Verbose
}

type LogClientsQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogClientsQuery) Reset() {
	*x = LogClientsQuery{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogClientsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogClientsQuery) ProtoMessage() {}

func (x *LogClientsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogClientsQuery.ProtoReflect.Descriptor instead.
func (*LogClientsQuery) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *LogClientsQuery) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type LogClientsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	LogClients    []string               `protobuf:"bytes,2,rep,name=LogClients,proto3" json:"LogClients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogClientsResult) Reset() {
	*x = LogClientsResult{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogClientsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogClientsResult) ProtoMessage() {}

func (x *LogClientsResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogClientsResult.ProtoReflect.Descriptor instead.
func (*LogClientsResult) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *LogClientsResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogClientsResult) GetLogClients() []string {
	if x != nil {
		return x.LogClients
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DatabasesQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabasesQuery) Reset() {
	*x = DatabasesQuery{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabasesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabasesQuery) ProtoMessage() {}

func (x *DatabasesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabasesQuery.ProtoReflect.Descriptor instead.
func (*DatabasesQuery) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *DatabasesQuery) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type DatabasesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Databases     []string               `protobuf:"bytes,2,rep,name=Databases,proto3" json:"Databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabasesResult) Reset() {
	*x = DatabasesResult{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabasesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabasesResult) ProtoMessage() {}

func (x *DatabasesResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabasesResult.ProtoReflect.Descriptor instead.
func (*DatabasesResult) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *DatabasesResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DatabasesResult) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TablesQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=Database,proto3" json:"Database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TablesQuery) Reset() {
	*x = TablesQuery{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TablesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablesQuery) ProtoMessage() {}

func (x *TablesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablesQuery.ProtoReflect.Descriptor instead.
func (*TablesQuery) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *TablesQuery) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type TablesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Tables        []string               `protobuf:"bytes,2,rep,name=Tables,proto3" json:"Tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TablesResult) Reset() {
	*x = TablesResult{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TablesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablesResult) ProtoMessage() {}

func (x *TablesResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablesResult.ProtoReflect.Descriptor instead.
func (*TablesResult) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *TablesResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TablesResult) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x04logs\x1a\n" +
	"logs.proto\"]\n" +
	"\tLogClient\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bDBPolicy\x18\x02 \x01(\x05R\bDBPolicy\x12$\n" +
	"\x05Level\x18\x03 \x01(\x0e2\x0e.logs.LogLevelR\x05Level\"+\n" +
	"\x0fLogClientsQuery\x12\x18\n" +
	"\aKeyword\x18\x01 \x01(\tR\aKeyword\"L\n" +
	"\x10LogClientsResult\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x1e\n" +
	"\n" +
	"LogClients\x18\x02 \x03(\tR\n" +
	"LogClients\"\x1e\n" +
	"\bDatabase\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\",\n" +
	"\x0eDatabasesQuery\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\"I\n" +
	"\x0fDatabasesResult\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x1c\n" +
	"\tDatabases\x18\x02 \x03(\tR\tDatabases\"\x1b\n" +
	"\x05Table\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\")\n" +
	"\vTablesQuery\x12\x1a\n" +
	"\bDatabase\x18\x01 \x01(\tR\bDatabase\"@\n" +
	"\fTablesResult\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x16\n" +
	"\x06Tables\x18\x02 \x03(\tR\x06Tables2\xc0\x01\n" +
	"\x10LogClientService\x12;\n" +
	"\n" +
	"GetClients\x12\x15.logs.LogClientsQuery\x1a\x16.logs.LogClientsResult\x12;\n" +
	"\fGetDatabases\x12\x14.logs.DatabasesQuery\x1a\x15.logs.DatabasesResult\x122\n" +
	"\tGetTables\x12\x11.logs.TablesQuery\x1a\x12.logs.TablesResultB\x1dZ\x1bgithub.com/DreamvatLab/logsb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_proto_goTypes = []any{
	(*LogClient)(nil),        // 0: logs.LogClient
	(*LogClientsQuery)(nil),  // 1: logs.LogClientsQuery
	(*LogClientsResult)(nil), // 2: logs.LogClientsResult
	(*Database)(nil),         // 3: logs.Database
	(*DatabasesQuery)(nil),   // 4: logs.DatabasesQuery
	(*DatabasesResult)(nil),  // 5: logs.DatabasesResult
	(*Table)(nil),            // 6: logs.Table
	(*TablesQuery)(nil),      // 7: logs.TablesQuery
	(*TablesResult)(nil),     // 8: logs.TablesResult
	(LogLevel)(0),            // 9: logs.LogLevel
}
var file_client_proto_depIdxs = []int32{
	9, // 0: logs.LogClient.Level:type_name -> logs.LogLevel
	1, // 1: logs.LogClientService.GetClients:input_type -> logs.LogClientsQuery
	4, // 2: logs.LogClientService.GetDatabases:input_type -> logs.DatabasesQuery
	7, // 3: logs.LogClientService.GetTables:input_type -> logs.TablesQuery
	2, // 4: logs.LogClientService.GetClients:output_type -> logs.LogClientsResult
	5, // 5: logs.LogClientService.GetDatabases:output_type -> logs.DatabasesResult
	8, // 6: logs.LogClientService.GetTables:output_type -> logs.TablesResult
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_logs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
