// v1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.22.3
// source: logs.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_Verbose    LogLevel = 0
	LogLevel_Debug      LogLevel = 1
	LogLevel_Infomation LogLevel = 2
	LogLevel_Warning    LogLevel = 3
	LogLevel_Error      LogLevel = 4
	LogLevel_Fatal      LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Verbose",
		1: "Debug",
		2: "Infomation",
		3: "Warning",
		4: "Error",
		5: "Fatal",
	}
	LogLevel_value = map[string]int32{
		"Verbose":    0,
		"Debug":      1,
		"Infomation": 2,
		"Warning":    3,
		"Error":      4,
		"Fatal":      5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logs_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_logs_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: db:"ID" bson:"_id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" db:"ID" bson:"_id"`
	// @gotags: db:"TraceNo"
	TraceNo string `protobuf:"bytes,2,opt,name=TraceNo,proto3" json:"TraceNo,omitempty" db:"TraceNo"`
	// @gotags: db:"User"
	User string `protobuf:"bytes,3,opt,name=User,proto3" json:"User,omitempty" db:"User"`
	// @gotags: db:"Message"
	Message string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty" db:"Message"`
	// @gotags: db:"Error"
	Error string `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty" db:"Error"`
	// @gotags: db:"StackTrace"
	StackTrace string `protobuf:"bytes,6,opt,name=StackTrace,proto3" json:"StackTrace,omitempty" db:"StackTrace"`
	// @gotags: db:"Payload"
	Payload string `protobuf:"bytes,7,opt,name=Payload,proto3" json:"Payload,omitempty" db:"Payload"`
	// @gotags: db:"Level"
	Level LogLevel `protobuf:"varint,8,opt,name=Level,proto3,enum=logs.LogLevel" json:"Level,omitempty" db:"Level"`
	// @gotags: db:"Flags"
	Flags int64 `protobuf:"varint,9,opt,name=Flags,proto3" json:"Flags,omitempty" db:"Flags"`
	// @gotags: db:"CreatedOnUtc"
	CreatedOnUtc  int64 `protobuf:"varint,10,opt,name=CreatedOnUtc,proto3" json:"CreatedOnUtc,omitempty" db:"CreatedOnUtc"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogEntry) GetTraceNo() string {
	if x != nil {
		return x.TraceNo
	}
	return ""
}

func (x *LogEntry) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogEntry) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *LogEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Verbose
}

func (x *LogEntry) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *LogEntry) GetCreatedOnUtc() int64 {
	if x != nil {
		return x.CreatedOnUtc
	}
	return 0
}

type WriteLogCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	LogEntry      *LogEntry              `protobuf:"bytes,2,opt,name=LogEntry,proto3" json:"LogEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogCommand) Reset() {
	*x = WriteLogCommand{}
	mi := &file_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogCommand) ProtoMessage() {}

func (x *WriteLogCommand) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogCommand.ProtoReflect.Descriptor instead.
func (*WriteLogCommand) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{1}
}

func (x *WriteLogCommand) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *WriteLogCommand) GetLogEntry() *LogEntry {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

type LogEntryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DBName        string                 `protobuf:"bytes,1,opt,name=DBName,proto3" json:"DBName,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryQuery) Reset() {
	*x = LogEntryQuery{}
	mi := &file_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryQuery) ProtoMessage() {}

func (x *LogEntryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryQuery.ProtoReflect.Descriptor instead.
func (*LogEntryQuery) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntryQuery) GetDBName() string {
	if x != nil {
		return x.DBName
	}
	return ""
}

func (x *LogEntryQuery) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *LogEntryQuery) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type LogEntryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	LogEntry      *LogEntry              `protobuf:"bytes,2,opt,name=LogEntry,proto3" json:"LogEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryResult) Reset() {
	*x = LogEntryResult{}
	mi := &file_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryResult) ProtoMessage() {}

func (x *LogEntryResult) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryResult.ProtoReflect.Descriptor instead.
func (*LogEntryResult) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntryResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntryResult) GetLogEntry() *LogEntry {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

type LogEntriesQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DBName        string                 `protobuf:"bytes,1,opt,name=DBName,proto3" json:"DBName,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	TraceNo       string                 `protobuf:"bytes,3,opt,name=TraceNo,proto3" json:"TraceNo,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=Error,proto3" json:"Error,omitempty"`
	StackTrace    string                 `protobuf:"bytes,7,opt,name=StackTrace,proto3" json:"StackTrace,omitempty"`
	OrderDir      string                 `protobuf:"bytes,8,opt,name=OrderDir,proto3" json:"OrderDir,omitempty"`
	StartTime     string                 `protobuf:"bytes,9,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,10,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Level         LogLevel               `protobuf:"varint,11,opt,name=Level,proto3,enum=logs.LogLevel" json:"Level,omitempty"`
	PageSize      int32                  `protobuf:"varint,12,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageIndex     int32                  `protobuf:"varint,13,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	OrderBy       int32                  `protobuf:"varint,14,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Flags         int64                  `protobuf:"varint,15,opt,name=Flags,proto3" json:"Flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntriesQuery) Reset() {
	*x = LogEntriesQuery{}
	mi := &file_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntriesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntriesQuery) ProtoMessage() {}

func (x *LogEntriesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntriesQuery.ProtoReflect.Descriptor instead.
func (*LogEntriesQuery) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntriesQuery) GetDBName() string {
	if x != nil {
		return x.DBName
	}
	return ""
}

func (x *LogEntriesQuery) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *LogEntriesQuery) GetTraceNo() string {
	if x != nil {
		return x.TraceNo
	}
	return ""
}

func (x *LogEntriesQuery) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LogEntriesQuery) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntriesQuery) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogEntriesQuery) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *LogEntriesQuery) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *LogEntriesQuery) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *LogEntriesQuery) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *LogEntriesQuery) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Verbose
}

func (x *LogEntriesQuery) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LogEntriesQuery) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *LogEntriesQuery) GetOrderBy() int32 {
	if x != nil {
		return x.OrderBy
	}
	return 0
}

func (x *LogEntriesQuery) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type LogEntriesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,3,rep,name=LogEntries,proto3" json:"LogEntries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntriesResult) Reset() {
	*x = LogEntriesResult{}
	mi := &file_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntriesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntriesResult) ProtoMessage() {}

func (x *LogEntriesResult) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntriesResult.ProtoReflect.Descriptor instead.
func (*LogEntriesResult) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntriesResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntriesResult) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *LogEntriesResult) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

var File_logs_proto protoreflect.FileDescriptor

const file_logs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"logs.proto\x12\x04logs\"\x92\x02\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aTraceNo\x18\x02 \x01(\tR\aTraceNo\x12\x12\n" +
	"\x04User\x18\x03 \x01(\tR\x04User\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage\x12\x14\n" +
	"\x05Error\x18\x05 \x01(\tR\x05Error\x12\x1e\n" +
	"\n" +
	"StackTrace\x18\x06 \x01(\tR\n" +
	"StackTrace\x12\x18\n" +
	"\aPayload\x18\a \x01(\tR\aPayload\x12$\n" +
	"\x05Level\x18\b \x01(\x0e2\x0e.logs.LogLevelR\x05Level\x12\x14\n" +
	"\x05Flags\x18\t \x01(\x03R\x05Flags\x12\"\n" +
	"\fCreatedOnUtc\x18\n" +
	" \x01(\x03R\fCreatedOnUtc\"Y\n" +
	"\x0fWriteLogCommand\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12*\n" +
	"\bLogEntry\x18\x02 \x01(\v2\x0e.logs.LogEntryR\bLogEntry\"U\n" +
	"\rLogEntryQuery\x12\x16\n" +
	"\x06DBName\x18\x01 \x01(\tR\x06DBName\x12\x1c\n" +
	"\tTableName\x18\x02 \x01(\tR\tTableName\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\"V\n" +
	"\x0eLogEntryResult\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12*\n" +
	"\bLogEntry\x18\x02 \x01(\v2\x0e.logs.LogEntryR\bLogEntry\"\xa9\x03\n" +
	"\x0fLogEntriesQuery\x12\x16\n" +
	"\x06DBName\x18\x01 \x01(\tR\x06DBName\x12\x1c\n" +
	"\tTableName\x18\x02 \x01(\tR\tTableName\x12\x18\n" +
	"\aTraceNo\x18\x03 \x01(\tR\aTraceNo\x12\x12\n" +
	"\x04User\x18\x04 \x01(\tR\x04User\x12\x18\n" +
	"\aMessage\x18\x05 \x01(\tR\aMessage\x12\x14\n" +
	"\x05Error\x18\x06 \x01(\tR\x05Error\x12\x1e\n" +
	"\n" +
	"StackTrace\x18\a \x01(\tR\n" +
	"StackTrace\x12\x1a\n" +
	"\bOrderDir\x18\b \x01(\tR\bOrderDir\x12\x1c\n" +
	"\tStartTime\x18\t \x01(\tR\tStartTime\x12\x18\n" +
	"\aEndTime\x18\n" +
	" \x01(\tR\aEndTime\x12$\n" +
	"\x05Level\x18\v \x01(\x0e2\x0e.logs.LogLevelR\x05Level\x12\x1a\n" +
	"\bPageSize\x18\f \x01(\x05R\bPageSize\x12\x1c\n" +
	"\tPageIndex\x18\r \x01(\x05R\tPageIndex\x12\x18\n" +
	"\aOrderBy\x18\x0e \x01(\x05R\aOrderBy\x12\x14\n" +
	"\x05Flags\x18\x0f \x01(\x03R\x05Flags\"|\n" +
	"\x10LogEntriesResult\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x03R\n" +
	"TotalCount\x12.\n" +
	"\n" +
	"LogEntries\x18\x03 \x03(\v2\x0e.logs.LogEntryR\n" +
	"LogEntries*U\n" +
	"\bLogLevel\x12\v\n" +
	"\aVerbose\x10\x00\x12\t\n" +
	"\x05Debug\x10\x01\x12\x0e\n" +
	"\n" +
	"Infomation\x10\x02\x12\v\n" +
	"\aWarning\x10\x03\x12\t\n" +
	"\x05Error\x10\x04\x12\t\n" +
	"\x05Fatal\x10\x052\xc9\x01\n" +
	"\x0fLogEntryService\x12<\n" +
	"\rWriteLogEntry\x12\x15.logs.WriteLogCommand\x1a\x14.logs.LogEntryResult\x128\n" +
	"\vGetLogEntry\x12\x13.logs.LogEntryQuery\x1a\x14.logs.LogEntryResult\x12>\n" +
	"\rGetLogEntries\x12\x15.logs.LogEntriesQuery\x1a\x16.logs.LogEntriesResultB\x1dZ\x1bgithub.com/DreamvatLab/logsb\x06proto3"

var (
	file_logs_proto_rawDescOnce sync.Once
	file_logs_proto_rawDescData []byte
)

func file_logs_proto_rawDescGZIP() []byte {
	file_logs_proto_rawDescOnce.Do(func() {
		file_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)))
	})
	return file_logs_proto_rawDescData
}

var file_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_logs_proto_goTypes = []any{
	(LogLevel)(0),            // 0: logs.LogLevel
	(*LogEntry)(nil),         // 1: logs.LogEntry
	(*WriteLogCommand)(nil),  // 2: logs.WriteLogCommand
	(*LogEntryQuery)(nil),    // 3: logs.LogEntryQuery
	(*LogEntryResult)(nil),   // 4: logs.LogEntryResult
	(*LogEntriesQuery)(nil),  // 5: logs.LogEntriesQuery
	(*LogEntriesResult)(nil), // 6: logs.LogEntriesResult
}
var file_logs_proto_depIdxs = []int32{
	0, // 0: logs.LogEntry.Level:type_name -> logs.LogLevel
	1, // 1: logs.WriteLogCommand.LogEntry:type_name -> logs.LogEntry
	1, // 2: logs.LogEntryResult.LogEntry:type_name -> logs.LogEntry
	0, // 3: logs.LogEntriesQuery.Level:type_name -> logs.LogLevel
	1, // 4: logs.LogEntriesResult.LogEntries:type_name -> logs.LogEntry
	2, // 5: logs.LogEntryService.WriteLogEntry:input_type -> logs.WriteLogCommand
	3, // 6: logs.LogEntryService.GetLogEntry:input_type -> logs.LogEntryQuery
	5, // 7: logs.LogEntryService.GetLogEntries:input_type -> logs.LogEntriesQuery
	4, // 8: logs.LogEntryService.WriteLogEntry:output_type -> logs.LogEntryResult
	4, // 9: logs.LogEntryService.GetLogEntry:output_type -> logs.LogEntryResult
	6, // 10: logs.LogEntryService.GetLogEntries:output_type -> logs.LogEntriesResult
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_logs_proto_init() }
func file_logs_proto_init() {
	if File_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_proto_goTypes,
		DependencyIndexes: file_logs_proto_depIdxs,
		EnumInfos:         file_logs_proto_enumTypes,
		MessageInfos:      file_logs_proto_msgTypes,
	}.Build()
	File_logs_proto = out.File
	file_logs_proto_goTypes = nil
	file_logs_proto_depIdxs = nil
}
